x-default-environment: &default-environment
  NODE_ENV: development
  TZ: "UTC"
  AUTH0_DOMAIN: "https://dev-0tc6bn14.eu.auth0.com"
  AUTH0_AUDIENCE: testing
  DB_HOST: db
  DB_NAME: &default-db-name travel_development
  DB_PASS: &default-db-password itsallgood
  DB_USER: &default-db-user app
  DB_PORT: 5432
  DB_HEALTH_CHECK_INTERVAL_SECONDS: 5
  DB_HEALTH_CHECK_TIMEOUT_SECONDS: 10
  DB_HEALTH_CHECK_RETRIES: 3
  DB_HEALTH_CHECK_START_PERIOD_SECONDS: 5
  TRAVCOM_DB_HOST: db_trav_com
  TRAVCOM_DB_USER: sa
  TRAVCOM_DB_PASS: &default-trav-com-db-password "DevPwd99!"
  TRAVCOM_DB_NAME: trav_com_development
  TRAVCOM_DB_PORT: 1433
  TRAVCOM_DB_TRUST_SERVER_CERTIFICATE_ENABLED: "true"
  RELEASE_TAG: "${RELEASE_TAG:-development}"
  GIT_COMMIT_HASH: "${GIT_COMMIT_HASH:-not-set}"

services:
  api:
    build:
      context: ./api
      dockerfile: development.Dockerfile
    env_file:
      - ./api/.env.development
    environment:
      <<: *default-environment
      TS_NODE_HISTORY: /usr/src/api/.ts_node_repl_history
    tty: true # allows attaching debugger, equivalent of docker exec -t
    init: true
    # stdin_open: true # equivalent of docker exec -i
    user: "${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}"
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/api
      - ./.gitignore:/usr/src/.gitignore
      - ./.prettierrc.yaml:/usr/src/.prettierrc.yaml
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: development.Dockerfile
    environment:
      <<: *default-environment
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/src/web
      - ./.gitignore:/usr/src/.gitignore
      - ./.prettierrc.yaml:/usr/src/.prettierrc.yaml
    depends_on:
      - api

  test_api:
    build:
      context: ./api
      dockerfile: development.Dockerfile
    command: /bin/true
    env_file:
      - ./api/.env.development
    environment:
      <<: *default-environment
      NODE_ENV: test
      DB_NAME: travel_test
      TRAVCOM_DB_NAME: trav_com_test
      DEFAULT_LOG_LEVEL: "info"
    tty: true
    volumes:
      - ./api:/usr/src/api
      - ./api/.env.development:/usr/src/api/.env.test
    depends_on:
      - db
      - db_trav_com

  test_web:
    build:
      context: ./web
      dockerfile: development.Dockerfile
    command: /bin/true
    environment:
      <<: *default-environment
      NODE_ENV: test
    tty: true
    volumes:
      - ./web:/usr/src/web

  db:
    image: "postgres:14.4"
    environment:
      <<: *default-environment
      POSTGRES_USER: *default-db-user
      POSTGRES_PASSWORD: *default-db-password
      POSTGRES_DB: *default-db-name
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Represents an external database for TravCom (a.k.a. Travel Computer Systems)
  db_trav_com:
    image: mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
    user: root
    environment:
      MSSQL_SA_PASSWORD: *default-trav-com-db-password # requires secure password
      TZ: "UTC"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_trav_com_data:/var/opt/mssql/data

  # For easily generating large PlantUML diagrams
  # Not relevant to production environment.
  # Accessible at http://localhost:9999
  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - 9999:8080
    environment:
      PLANTUML_LIMIT_SIZE: 8192
    profiles:
      - design

volumes:
  db_data:
  db_trav_com_data:
